language: generic
sudo: false

env:
  BYOND_MAJOR="509"
  BYOND_MINOR="1318"
  MACRO_COUNT=1158
  
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
  
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
  
install:
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh

script:
  - shopt -s globstar
  - (! grep 'step_[xy]' maps/**/*.dmm)
  - (! find nano/templates/ -type f -exec md5sum {} + | sort | uniq -D -w 32 | grep nano)
  - (! grep -E "<\s*span\s+class\s*=\s*('[^'>]+|[^'>]+')\s*>" **/*.dm)
  - (num=`grep -E '\\\\(red|blue|green|black|b|i[^mc])' **/*.dm | wc -l`; echo "$num escapes (expecting ${MACRO_COUNT} or less)"; [ $num -le ${MACRO_COUNT} ])
  - md5sum -c - <<< "3ef44160a5c9931f1b83db8a9b6c393c *yonaguni.int"
  - md5sum -c - <<< "88490b460c26947f5ec1ab1bb9fa9f17 *html/changelogs/example.yml"
  - python tools/TagMatcher/tag-matcher.py ../..
  - python tools/GenerateChangelog/ss13_genchangelog.py html/changelog.html html/changelogs --dry-run
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - DreamMaker yonaguni.dme

